### ISSUE TITLE
Didnt receive my ETH

### ISSUE THREAD

**Issue by Lightningwave** [larvalabs/cryptopunks#1]
Hi I sold my ultimate Cryptopunks but I didn't receive my ETH yet
Now I am very sad to lose my Cryptopunks

**Comment by pents90** [comment]
Hey Lightningwave, very sorry that you are experiencing trouble. We have a bug in the contract that prevents the ETH from going out to the seller. Instead, it is available to the buyer instead, so they can simply take the money back after buying the punk. We are working on migrating to a new contract that will solve the problem. We *may* also be able to revert all the sales so you would get your punks back. We'll keep you updated.

**Comment by cryptopunk777** [comment]
Hi, I bought a punk for 0.1 ETH. I would like to keep it after the transition to the new contract as well, because I like it very much.  Experiencing how the value of some punks appreciate, it will be unlikely that the original owner will offer it once more for sale for this price and even with the same price it will be unlikely that I will be able to buy it again, because I am not sittng next to my computer all the time. I haven´t withdrawn the price from the contract yet as abuyer, and I am not planning to do so. Will you take into consideration this as well when you design the the new contract and the transition?

**Comment by pents90** [comment]
@cryptopunk777 what punk # did you buy?

**Comment by cryptopunk777** [comment]
Hi, thank you for the quick response. I would not like to identify myself and my ETH account to the public. Can I write to you the number in a mail or share with you in another way?

**Comment by pents90** [comment]
Sure, email me: watkinson _at_ gmail.

**Comment by coltsnation55** [comment]
Can you please assist me with getting a cryptopunk?

**Comment by drobsokc** [comment]
I bought CryptoPunk #987 and would like to keep that punk. Sold to 0xc2f87f for 0.0033 Ether ($1.16 USD) in transaction 0xb9b37ec4.

**Comment by pents90** [comment]
@drobsokc that was us who sold you that punk, so we'll happily resell it to you at the same price once we get everything fixed!

**Comment by drobsokc** [comment]
@pents90 Thank you!

**Comment by Lightningwave** [comment]
@pents90 so you guys take all the zombies? =(

**Comment by brh55** [comment]
@Lightningwave surprisingly they don't have any zombies currently, but considering they sold one at $1.16 that's pretty awesome 👍 🍾

**Comment by drobsokc** [comment]
@pents90, was CryptoPunk #987 the first purchase?

**Comment by drobsokc** [comment]
@pents90, I made a bid for .0033 ETH for punk 987 :)

**Comment by megamattron** [comment]
Punk 987 has been transferred to @drobsokc !
